### ISSUE TITLE
[BUG]  No es tan grave... es algo ortográfico que vi

### ISSUE THREAD

**Issue by lukedalmau** [Covid19-Cuba-Efforts/covid19cuba-app#63]
**Describe the bug**
A ver no es tanto un bug como tal pero extranjeros lo pusieron con g en la q se descarga dsd apklis
Ah y que paso con las estadisticas comparativas con otros paises que ya no estan?🥺

**Comment by Yeikel200** [comment]
@lukedalmau Las estadísticas comparativas con otros países no se ven a causa de que se hace infinito el scroll, al parecer es solo en algunos teléfonos, yo tengo un Xiaomi Note 7 y no se ve tampoco, 
![Screenshot_2020-03-30-09-56-29-111_club postdata covid19cuba](https://user-images.githubusercontent.com/26438532/77947755-66942d00-7292-11ea-8063-157e9ca4cdd2.jpg)
probé en actualizarla en el de una amistad y funciona a la perfección todo

**Comment by stdevCbermudez** [comment]
@leynier viste ya lo que dice @lukedalmau en apklis. Que pasa con las estadísticas comparativas?

**Comment by leynier** [comment]
> @lukedalmau Las estadísticas comparativas con otros países no se ven a causa de que se hace infinito el scroll, al parecer es solo en algunos teléfonos, yo tengo un Xiaomi Note 7 y no se ve tampoco,
> ![Screenshot_2020-03-30-09-56-29-111_club postdata covid19cuba](https://user-images.githubusercontent.com/26438532/77947755-66942d00-7292-11ea-8063-157e9ca4cdd2.jpg)
> probé en actualizarla en el de una amistad y funciona a la perfección todo

Y en su Xiaomi Note 7 después de actualizar sigue saliendo el recuadro gris?

**Comment by Yeikel200** [comment]
Si, todo estaba bien hasta que actualicé a la versión 0.2.0

**Comment by leynier** [comment]
> Si, todo estaba bien hasta que actualicé a la versión 0.2.0

Digo actualizar la información? Deslice hacia abajo cuando está al principio del app.

**Comment by Yeikel200** [comment]
Si se desliza, lo que tiene el scroll infinito después de _**evolución de casos por día**_

**Comment by stdevCbermudez** [comment]
> Si se desliza, lo que tiene el scroll infinito después de _**evolución de casos por día**_

Preguntaba leynier que si haces que se actualize la información, después que lo hace sigue pasando lo mismo?

**Comment by leynier** [comment]
> Si se desliza, lo que tiene el scroll infinito después de _**evolución de casos por día**_

Por favor, necesito que haga la siguiente prueba? Parece en el principio del app, y tocando el dedo hacia abajo como intentando ir hacia arriba, le va a salir un icono de recargar, similar a otras apps como Gmail, etc, esto es para actualizar la información y descargar la última información disponible. Luego de eso, digame si sigue saliendo el error.

**Comment by Yeikel200** [comment]
No, ya no me sale el error al actualizar los datos de la app !!

**Comment by leynier** [comment]
> No, ya no me sale el error al actualizar los datos de la app !!

Muchas gracias!! Ya no debería salir más el error.

**Comment by lukedalmau** [comment]
Muchas gracias a todos...😁👌🏻 la red esta lenta asibq me dicen si ya cierro el issue

**Comment by stdevCbermudez** [comment]
> Muchas gracias a todos...😁👌🏻 la red esta lenta asibq me dicen si ya cierro el issue

Cuando suba el pull request lo cerramos 👍

**Comment by lukedalmau** [comment]
Ok👌🏻👌🏻👌🏻
